python3 -m src.neus.main wandb.name=teddy wandb.mode=online dataset.nerf_synthetic.scene=teddy
python3 -m src.neus.main wandb.name=chair wandb.mode=online dataset.nerf_synthetic.scene=chair
python3 -m src.neus.main wandb.name=drums wandb.mode=online dataset.nerf_synthetic.scene=drums
python3 -m src.neus.main wandb.name=ficus wandb.mode=online dataset.nerf_synthetic.scene=ficus
python3 -m src.neus.main wandb.name=hotdog wandb.mode=online dataset.nerf_synthetic.scene=hotdog
python3 -m src.neus.main wandb.name=lego wandb.mode=online dataset.nerf_synthetic.scene=lego
python3 -m src.neus.main wandb.name=materials wandb.mode=online dataset.nerf_synthetic.scene=materials
python3 -m src.neus.main wandb.name=mic wandb.mode=online dataset.nerf_synthetic.scene=mic
python3 -m src.neus.main wandb.name=ship wandb.mode=online dataset.nerf_synthetic.scene=ship
