defaults:
  - dataset: nerf_synthetic
  - model: neus

wandb:
  project: styleneus
  name: styleneus
  entity: scene-representation-group
  mode: offline

validation:
  batch_size: 4
  num_rays: 256
  num_workers: 0
  interval: 256
  preview_image_scale: 0.2

training:
  batch_size: 4
  num_rays: 256
  num_workers: 0
  optim:
    lr: 5e-4
  checkpointing:
    every_n_train_steps: 5000
    save_top_k: -1

rendering:
  checkpoint: samples/chair_checkpoint.ckpt
  deformation: samples/chair_deformation.pickle

meshing:
  resolution: 384
  checkpoint: model.ckpt
  path: mesh.obj

# Mode can be either "train", "mesh", or "render"
mode: train
