defaults:
  - dataset: nerf_synthetic
  - model: neus

wandb:
  project: styleneus
  name: styleneus
  entity: charatan
  mode: offline

validation:
  batch_size: 4
  num_rays: 256
  num_workers: 0
  interval: 256
  preview_image_scale: 0.2

training:
  batch_size: 4
  num_rays: 256
  num_workers: 0
  optim:
    lr: 5e-4
  checkpointing:
    every_n_train_steps: 5000
    save_top_k: -1

rendering:
  checkpoint: samples/mic_checkpoint.ckpt
  undeformed: samples/mic_original.stl
  deformed: samples/mic_stylized.stl

# Mode can be either "train" or "render"
mode: train
